services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pizza-network

  # Order Service
  order-service:
    image: ghcr.io/simonstreuli/order-service:latest
#    build:
#      context: .
#      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      PAYMENT_SERVICE_URL: http://payment-service:8081
    depends_on:
      rabbitmq:
        condition: service_healthy
      payment-service:
        condition: service_started
    networks:
      - pizza-network

  # Payment Service
  payment-service:
    image: ghcr.io/norisgiro/payment-service:1.0.0
#    build:
#      context: .
#      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      PAYMENT_FAILURE_RATE: 0.2
      PAYMENT_DELAY_MIN: 100
      PAYMENT_DELAY_MAX: 500
    networks:
      - pizza-network

  # Kitchen Service (can be scaled)
  kitchen-service:
    image: ghcr.io/franmatkovic/kitchen-service:latest
#    build:
#      context: .
#      dockerfile: kitchen-service/Dockerfile
    ports:
      - "8082"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      KITCHEN_PREPARATION_TIME_MIN: 5000
      KITCHEN_PREPARATION_TIME_MAX: 10000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - pizza-network

  # Delivery Service
  delivery-service:
    image: ghcr.io/mouadbourbian/modul-321-delivery-service:latest
#    build:
#      context: .
#      dockerfile: delivery-service/Dockerfile
    container_name: delivery-service
    ports:
      - "8083:8083"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - pizza-network

  # Frontend Service
  frontend:
    image: ghcr.io/simonstreuli/frontend:latest
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - delivery-service
    networks:
      - pizza-network

networks:
  pizza-network:
    driver: bridge
